In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
import pandas as pd

df1 = pd.read_csv('/content/drive/MyDrive/Project_NLP/du_lieu_bao_nguoi_lao_dong/true.csv',usecols=[0])
df2 = pd.read_csv('/content/drive/MyDrive/Project_NLP/du_lieu_bao_suc_khoe_doi_song/true.csv',usecols=[0])
df3=pd.read_csv('/content/drive/MyDrive/Project_NLP/du_lieu_bao_tien_phong/true.csv',usecols=[0])
megred_df=pd.read_csv('/content/drive/MyDrive/merged.csv',usecols=[0])
merged_df1_df2 = pd.concat([df1, df2], ignore_index=True)
merged_df1_df2_df3 = pd.concat([merged_df1_df2 , df3], ignore_index=True)
df= pd.concat([merged_df1_df2_df3 , merged], ignore_index=True)

In [ ]:
df

                                                  title
0     Cán bộ công an tử vong vì tai nạn giao thông h...
1     Chủ tịch UBND TP HCM: Chọn 38 trung tâm giải q...
2     Dùng cần cẩu giải cứu 2 người đi xe máy rơi xu...
3     Khánh Hòa phát động phong trào thi đua Ngày kh...
4     Khói bụi trắng bao trùm khu vực gần nhà máy th...
...                                                 ...
7090  Đầu tháng 7 Hà Nội mưa to, gió lớn . Diễn biến...
7091  Cuối tháng 6 Hà Nội có lúc có mưa rào và dông....
7092  Hà Nội có mưa dông kéo dài tới khi nào? . Trun...
7093  Hà Nội nắng gián đoạn, ngày oi nóng có mưa lớn...
7094  Hà Nội dịu nhẹ có mưa lớn về chiều và đêm. The...

[7095 rows x 1 columns]

In [ ]:
df['label']=1

In [ ]:
df

                                                  title  label
0     Cán bộ công an tử vong vì tai nạn giao thông h...      1
1     Chủ tịch UBND TP HCM: Chọn 38 trung tâm giải q...      1
2     Dùng cần cẩu giải cứu 2 người đi xe máy rơi xu...      1
3     Khánh Hòa phát động phong trào thi đua Ngày kh...      1
4     Khói bụi trắng bao trùm khu vực gần nhà máy th...      1
...                                                 ...    ...
7090  Đầu tháng 7 Hà Nội mưa to, gió lớn . Diễn biến...      1
7091  Cuối tháng 6 Hà Nội có lúc có mưa rào và dông....      1
7092  Hà Nội có mưa dông kéo dài tới khi nào? . Trun...      1
7093  Hà Nội nắng gián đoạn, ngày oi nóng có mưa lớn...      1
7094  Hà Nội dịu nhẹ có mưa lớn về chiều và đêm. The...      1

[7095 rows x 2 columns]

In [ ]:
df.rename(columns={'title': 'text'}, inplace=True)

In [ ]:
fake_news=pd.read_csv('/content/drive/MyDrive/crawl_fake_news.csv')
fake_true_news=pd.read_csv('/content/drive/MyDrive/Project_NLP/merged_fake_news_dataset.csv')

In [ ]:
fake_true_news

       Unnamed: 0                                               text  label
0               0  THĂNG CẤP BẬC HÀM ĐỐI VỚI 2 CÁN BỘ, CHIẾN SỸ H...      0
1               2  TƯ VẤN MÙA THI: Cách nộp hồ sơ để trúng tuyển ...      0
2               3  Cơ quan Cạnh tranh và Thị trường Anh quyết địn...      0
3               4  Thêm 7 ca tại Quảng Nam liên quan đến hành khá...      0
4               5  Trong giờ học Thể dụ‌c do thầy giáo Nguyễn Văn...      0
...           ...                                                ...    ...
50003       50055  BRUSSELS (Reuters) - Các đồng minh NATO hôm th...      1
50004       50056  LONDON (Reuters) - LexisNexis, nhà cung cấp th...      1
50005       50057  MINSK (Reuters) - Dưới bóng các nhà máy thời X...      1
50006       50058  MOSCOW (Reuters) - Bộ trưởng Ngoại giao Vatica...      1
50007       50059  JAKARTA (Reuters) - Hôm thứ Ba, hai bộ trưởng ...      1

[50008 rows x 3 columns]

In [ ]:
merged_df=pd.concat([df,fake_news], ignore_index=True)
combined_df=pd.concat([merged_df,fake_true_news], ignore_index=True)

In [ ]:
combined_df

                                                    text  label  Unnamed: 0
0      Cán bộ công an tử vong vì tai nạn giao thông h...      1         NaN
1      Chủ tịch UBND TP HCM: Chọn 38 trung tâm giải q...      1         NaN
2      Dùng cần cẩu giải cứu 2 người đi xe máy rơi xu...      1         NaN
3      Khánh Hòa phát động phong trào thi đua Ngày kh...      1         NaN
4      Khói bụi trắng bao trùm khu vực gần nhà máy th...      1         NaN
...                                                  ...    ...         ...
57458  BRUSSELS (Reuters) - Các đồng minh NATO hôm th...      1     50055.0
57459  LONDON (Reuters) - LexisNexis, nhà cung cấp th...      1     50056.0
57460  MINSK (Reuters) - Dưới bóng các nhà máy thời X...      1     50057.0
57461  MOSCOW (Reuters) - Bộ trưởng Ngoại giao Vatica...      1     50058.0
57462  JAKARTA (Reuters) - Hôm thứ Ba, hai bộ trưởng ...      1     50059.0

[57463 rows x 3 columns]

In [ ]:
combined_df = combined_df[['text', 'label']]

In [ ]:
combined_df.to_csv('final_merged.csv', index=False)